/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hzgnjupt_demo_jni_JniDemo */

#ifndef _Included_hzgnjupt_demo_jni_JniDemo
#define _Included_hzgnjupt_demo_jni_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hzgnjupt_demo_jni_JniDemo
 * Method:    argByteArray
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_hzgnjupt_demo_jni_JniDemo_argByteArray
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     hzgnjupt_demo_jni_JniDemo
 * Method:    retByteArray
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_hzgnjupt_demo_jni_JniDemo_retByteArray
  (JNIEnv *, jobject);

/*
 * Class:     hzgnjupt_demo_jni_JniDemo
 * Method:    argString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hzgnjupt_demo_jni_JniDemo_argString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hzgnjupt_demo_jni_JniDemo
 * Method:    retString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hzgnjupt_demo_jni_JniDemo_retString
  (JNIEnv *, jobject);

/*
 * Class:     hzgnjupt_demo_jni_JniDemo
 * Method:    argretInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_hzgnjupt_demo_jni_JniDemo_argretInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     hzgnjupt_demo_jni_JniDemo
 * Method:    argretDouble
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_hzgnjupt_demo_jni_JniDemo_argretDouble
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
